### Get all users
GET http://localhost:5000
Accept: application/json

###

### get user details by ID
GET  http://localhost:5000/user-details/a93cc894-c087-4c33-82fe-27b8ac42bd56
Content-Type: application/json

###

### Get a user by ID
POST http://localhost:5000/user-details
Content-Type: application/json

{
"first_name": "John",
        "last_name": "Doe",
        "current_position": "Software Engineer",
        "looking_for_position": "Senior Software Engineer",
        "skills": "Python, Flask, SQLAlchemy",
        "phone_number": "123-456-7890"
}

###

### get resume for user by ID
GET  http://localhost:5000/user_resume/7cfc13dc-e197-4f59-b3de-b6480d5fef85
Content-Type: application/json

###

### get linked in profile for user by ID
GET  http://localhost:5000/linked_in_profile/7cfc13dc-e197-4f59-b3de-b6480d5fef85
Content-Type: application/json

###

### get leet code exercises for user by ID
GET  http://localhost:5000/leet_code_exercises/7cfc13dc-e197-4f59-b3de-b6480d5fef85
Content-Type: application/json

###

### get mock interview for user by ID
GET  http://localhost:5000/mock_interview/7cfc13dc-e197-4f59-b3de-b6480d5fef85
Content-Type: application/json

###

### get salary negotiation for user by ID
GET  http://localhost:5000/salary_negotiation/7cfc13dc-e197-4f59-b3de-b6480d5fef85
Content-Type: application/json